/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 */

#include <stdio.h>

#define MAX 4000000

void fib(int a, int b, long *sum);

int main()
{
    int i;
    int a   = 1;
    int b   = 2;
    long sum = 2;

    fib(a, b, &sum);

    printf("SUM = %d\n", sum);
}

void fib(int a, int b, long *sum)
{
    int next = a + b;

    if ( next % 2 == 0 )
    {
        *sum += next;
    }

    if ( next <= MAX )
    {
        fib(b, next, sum);
    }

    return;
}

