#!/usr/bin/perl

# Problem:
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

use strict;
use warnings;

my $four_million = 4000000;
my $sum          = 2;
my $last_value   = 2;

my @fibs = ( 1, 2 );

while ( $last_value < $four_million )
{
    $last_value = $fibs[-1] + $fibs[-2];

    push @fibs, $last_value;

    print "$last_value";

    if ( ! ( $last_value % 2 ) )
    {
        $sum += $last_value;
        print "    NEW SUM = $sum";
    }

    print "\n";
}

print "\nSUM = $sum\n";
